/**
 * @export
 * @enum {string}
 */
export enum TransactionType {
    FAILED = 'FAILED',
    DEBITPAYMENT = 'DEBIT_PAYMENT',
    CREDITPAYMENT = 'CREDIT_PAYMENT',
    CREDITDEPOSIT = 'CREDIT_DEPOSIT',
    DEBITWITHDRAWAL = 'DEBIT_WITHDRAWAL',
    CANCELWITHDRAWAL = 'CANCEL_WITHDRAWAL',
    DEBITOUTGOINGPAYMENT = 'DEBIT_OUTGOING_PAYMENT',
    CREDITINCOMINGPAYMENT = 'CREDIT_INCOMING_PAYMENT',
    EXCHANGEBUY = 'EXCHANGE_BUY',
    EXCHANGESELL = 'EXCHANGE_SELL'
}