/**
 * SubscriptionType
 */
export enum SubscriptionType {
  OFFCHAIN_WITHDRAWAL = 'OFFCHAIN_WITHDRAWAL',
  ACCOUNT_BALANCE_LIMIT = 'ACCOUNT_BALANCE_LIMIT',
  ACCOUNT_INCOMING_BLOCKCHAIN_TRANSACTION = 'ACCOUNT_INCOMING_BLOCKCHAIN_TRANSACTION',
  ACCOUNT_PENDING_BLOCKCHAIN_TRANSACTION = 'ACCOUNT_PENDING_BLOCKCHAIN_TRANSACTION',
  KMS_FAILED_TX = 'KMS_FAILED_TX',
  KMS_COMPLETED_TX = 'KMS_COMPLETED_TX',
  TRANSACTION_HISTORY_REPORT = 'TRANSACTION_HISTORY_REPORT',
  CUSTOMER_TRADE_MATCH = 'CUSTOMER_TRADE_MATCH',
  CUSTOMER_PARTIAL_TRADE_MATCH = 'CUSTOMER_PARTIAL_TRADE_MATCH',
  TRANSACTION_IN_THE_BLOCK = 'TRANSACTION_IN_THE_BLOCK',
  ADDRESS_TRANSACTION = 'ADDRESS_TRANSACTION',
}
