/**
 * SubscriptionType
 */
export enum SubscriptionType {
  ACCOUNT_BALANCE_LIMIT = 'ACCOUNT_BALANCE_LIMIT',
  CUSTOMER_TRADE_MATCH = 'CUSTOMER_TRADE_MATCH',
  KMS_COMPLETED_TX = 'KMS_COMPLETED_TX',
  KMS_FAILED_TX = 'KMS_FAILED_TX',
  OFFCHAIN_WITHDRAWAL = 'OFFCHAIN_WITHDRAWAL',
  ACCOUNT_PENDING_BLOCKCHAIN_TRANSACTION = 'ACCOUNT_PENDING_BLOCKCHAIN_TRANSACTION',
  TRANSACTION_HISTORY_REPORT = 'TRANSACTION_HISTORY_REPORT',
  ACCOUNT_INCOMING_BLOCKCHAIN_TRANSACTION = 'ACCOUNT_INCOMING_BLOCKCHAIN_TRANSACTION',
  COMPLETE_BLOCKCHAIN_TRANSACTION = 'COMPLETE_BLOCKCHAIN_TRANSACTION',
}
