export enum Currency {
  BTC = "BTC",
  BCH = "BCH",
  LTC = "LTC",
  CELO = "CELO",
  /**
   * @deprecated Use `KAIA` instead
   */
  KLAY = "KLAY",
  ONE = "ONE",
  CUSD = "CUSD",
  CEUR = "CEUR",
  ETH = "ETH",
  ETC = "ETC",
  XRP = "XRP",
  XLM = "XLM",
  DOGE = "DOGE",
  VET = "VET",
  NEO = "NEO",
  BSC = "BSC",
  CAKE = "CAKE",
  ZIL = "ZIL",
  BUSD_BSC = "BUSD_BSC",
  B2U_BSC = "B2U_BSC",
  BETH = "BETH",
  GAMEE = "GAMEE",
  BBTC = "BBTC",
  BADA = "BADA",
  RMD = "RMD",
  WBNB = "WBNB",
  BDOT = "BDOT",
  BXRP = "BXRP",
  BLTC = "BLTC",
  BBCH = "BBCH",
  MATIC = "MATIC",
  USDC_MATIC = "USDC_MATIC",
  USDC_MATIC_NATIVE = "USDC_MATIC_NATIVE",
  USDC_BSC = "USDC_BSC",
  USDC_SOL = "USDC_SOL",
  USDT = "USDT",
  GMC = "GMC",
  GMC_BSC = "GMC_BSC",
  FLOW = "FLOW",
  FUSD = "FUSD",
  USDT_TRON = "USDT_TRON",
  INRT_TRON = "INRT_TRON",
  TRON = "TRON",
  LEO = "LEO",
  LINK = "LINK",
  INTENT = "INTENT",
  EURTENT = "EURTENT",
  GOLDAX = "GOLDAX",
  LISK = "LISK",
  WBTC = "WBTC",
  UNI = "UNI",
  SOL = "SOL",
  FREE = "FREE",
  MKR = "MKR",
  USDC = "USDC",
  MATIC_ETH = "MATIC_ETH",
  POL_ETH = "POL_ETH",
  BAT = "BAT",
  TUSD = "TUSD",
  BUSD = "BUSD",
  PAX = "PAX",
  PLTC = "PLTC",
  XCON = "XCON",
  REVV = "REVV",
  SAND = "SAND",
  MMY = "MMY",
  PAXG = "PAXG",
  HAG = "HAG",
  ADA = "ADA",
  XDC = "XDC",
  LATOKEN = "LATOKEN",
  USDT_MATIC = "USDT_MATIC",
  EGLD = "EGLD",
  ALGO = "ALGO",
  KCS = "KCS",
  COIIN = "COIIN",
  COIIN_BSC = "COIIN_BSC",
  GLMR = "GLMR",
  EOS = "EOS",
  AVAX = "AVAX",
  FTM = "FTM",
  ETH_ARB = "ETH_ARB",
  ETH_OP = "ETH_OP",
  NEAR = "NEAR",
  CRO = "CRO",
  RSK = "RSK",
  AURORA = "AURORA",
  GNO = "GNO",
  DOT = "DOT",
  KSM = "KSM",
  OASIS = "OASIS",
  PALM = "PALM",
  TEZOS = "TEZOS",
  ZCASH = "ZCASH",
  ZEC = "ZEC",
  ZEN = "ZEN",
  CHZ = "CHZ",
  ISLM = "ISLM",
  FLR = "FLR",
  ETH_BASE = "ETH_BASE",
  KADENA = "KADENA",
  ROSTRUM = "ROSTRUM",
  ATOM = "ATOM",
  IOTA = "IOTA",
  ELECTRUM = "ELECTRUM",
  CSPR = "CSPR",
  TON = "TON",
  ZK_SYNC = "ZK_SYNC",
  USDC_ARB = "USDC_ARB",
  USDC_OP = "USDC_OP",
  USDC_BASE = "USDC_BASE",
  USDT_ARB = "USDT_ARB",
  USDT_OP = "USDT_OP",
  USDT_BASE = "USDT_BASE",
  RON = "RON",
  S = "S",
  KAIA = "KAIA",
  BERA = "BERA",
}

export const ERC20_CURRENCIES = [
  Currency.USDT.toString(),
  Currency.LATOKEN.toString(),
  Currency.LEO.toString(),
  Currency.LINK.toString(),
  Currency.UNI.toString(),
  Currency.FREE.toString(),
  Currency.MKR.toString(),
  Currency.BUSD.toString(),
  Currency.USDC.toString(),
  Currency.MATIC_ETH.toString(),
  Currency.POL_ETH.toString(),
  Currency.BAT.toString(),
  Currency.WBTC.toString(),
  Currency.TUSD.toString(),
  Currency.PAX.toString(),
  Currency.PAXG.toString(),
  Currency.PLTC.toString(),
  Currency.XCON.toString(),
  Currency.MMY.toString(),
  Currency.COIIN.toString(),
  Currency.REVV.toString(),
  Currency.SAND.toString(),
  Currency.GMC.toString(),
];

export const BEP20_CURRENCIES = [
  Currency.BETH.toString(),
  Currency.BBTC.toString(),
  Currency.RMD.toString(),
  Currency.USDC_BSC.toString(),
  Currency.COIIN_BSC.toString(),
  Currency.B2U_BSC.toString(),
  Currency.BADA.toString(),
  Currency.WBNB.toString(),
  Currency.GMC_BSC.toString(),
  Currency.BDOT.toString(),
  Currency.BXRP.toString(),
  Currency.BLTC.toString(),
  Currency.BBCH.toString(),
  Currency.HAG.toString(),
  Currency.CAKE.toString(),
  Currency.BUSD_BSC.toString(),
];

export const MATIC20_CURRENCIES = [
  Currency.USDC_MATIC.toString(),
  Currency.USDC_MATIC_NATIVE.toString(),
  Currency.GAMEE.toString(),
  Currency.INTENT.toString(),
  Currency.EURTENT.toString(),
  Currency.GOLDAX.toString(),
  Currency.USDT_MATIC.toString(),
];

export const ETH_BASED_CURRENCIES = [
  Currency.ETH.toString(),
  ...ERC20_CURRENCIES,
];

export const MATIC_BASED_CURRENCIES = [
  Currency.MATIC.toString(),
  ...MATIC20_CURRENCIES,
];

export const BSC_BASED_CURRENCIES = [
  Currency.BSC.toString(),
  ...BEP20_CURRENCIES,
];

export const ARB_CURRENCIES = [
  Currency.USDC_ARB.toString(),
  Currency.USDT_ARB.toString(),
];
export const ARB_BASED_CURRENCIES = [
  Currency.ETH_ARB.toString(),
  ...ARB_CURRENCIES,
];

export const OPTIMISM_CURRENCIES = [
  Currency.USDC_OP.toString(),
  Currency.USDT_OP.toString(),
];
export const OPTIMISM_BASED_CURRENCIES = [
  Currency.ETH_OP.toString(),
  ...OPTIMISM_CURRENCIES,
];

export const BASE_CURRENCIES = [
  Currency.USDC_BASE.toString(),
  Currency.USDT_BASE.toString(),
];
export const BASE_BASED_CURRENCIES = [
  Currency.ETH_BASE.toString(),
  ...BASE_CURRENCIES,
];
