import { AddressEventNotificationChain, Chain, Network } from '../dto'

export const Constant = {
  TATUM_API_URL: {
    V1: 'https://api.tatum.io/v3/',
    V2: 'https://api.tatum.com/v1/',
  },
  NETWORK: {
    ChainMapInverse: {
      [AddressEventNotificationChain.ETH]: Chain.Ethereum,
      [AddressEventNotificationChain.SOL]: Chain.Solana,
      [AddressEventNotificationChain.MATIC]: Chain.Polygon,
      [AddressEventNotificationChain.CELO]: Chain.Celo,
      [AddressEventNotificationChain.KLAY]: Chain.Klaytn,
      [AddressEventNotificationChain.BTC]: Chain.Bitcoin,
      [AddressEventNotificationChain.LTC]: Chain.Litecoin,
      [AddressEventNotificationChain.BCH]: Chain.BitcoinCash,
      [AddressEventNotificationChain.DOGE]: Chain.Dogecoin,
      [AddressEventNotificationChain.TRON]: Chain.Tron,
      [AddressEventNotificationChain.BSC]: Chain.BinanceSmartChain,
    },
  },
  RPC: {
    MAINNETS: [
      Network.ALGORAND,
      Network.ARBITRUM_NOVA,
      Network.ARBITRUM_ONE,
      Network.AURORA,
      Network.AVALANCHE_C,
      Network.AVALANCHE_P,
      Network.AVALANCHE_X,
      Network.BINANCE_SMART_CHAIN,
      Network.BITCOIN,
      Network.BITCOIN_CASH,
      Network.CARDANO,
      Network.CELO,
      Network.CRONOS,
      Network.DOGECOIN,
      Network.EOS,
      Network.ETHEREUM,
      Network.ETHEREUM_CLASSIC,
      Network.FANTOM,
      Network.FLOW,
      Network.GNOSIS,
      Network.HARMONY_ONE_SHARD_0,
      Network.KLAYTN,
      Network.KUCOIN,
      Network.LITECOIN,
      Network.MULTIVERSX,
      Network.NEAR,
      Network.OASIS,
      Network.OPTIMISM,
      Network.PALM,
      Network.POLYGON,
      Network.POLKADOT,
      Network.RSK,
      Network.SOLANA,
      Network.STELLAR,
      Network.TEZOS,
      Network.TRON,
      Network.VECHAIN,
      Network.XDC,
      Network.XRP,
      Network.ZCASH,
      Network.ZILLIQA,
    ],
    TESTNETS: [
      Network.ALGORAND_TESTNET,
      Network.ARBITRUM_NOVA_TESTNET,
      Network.AURORA_TESTNET,
      Network.AVALANCHE_C_TESTNET,
      Network.AVALANCHE_P_TESTNET,
      Network.AVALANCHE_X_TESTNET,
      Network.BINANCE_SMART_CHAIN_TESTNET,
      Network.BITCOIN_TESTNET,
      Network.BITCOIN_CASH_TESTNET,
      Network.CARDANO_PREPROD,
      Network.CELO_ALFAJORES,
      Network.CRONOS_TESTNET,
      Network.DOGECOIN_TESTNET,
      Network.ETHEREUM_GOERLI,
      Network.ETHEREUM_SEPOLIA,
      Network.EOS_TESTNET,
      Network.FANTOM_TESTNET,
      Network.FLOW_TESTNET,
      Network.GNOSIS_TESTNET,
      Network.HARMONY_ONE_TESTNET_SHARD_0,
      Network.KLAYTN_BAOBAB,
      Network.KUCOIN_TESTNET,
      Network.LITECOIN_TESTNET,
      Network.MULTIVERSX_TESTNET,
      Network.NEAR_TESTNET,
      Network.OASIS_TESTNET,
      Network.OPTIMISM_TESTNET,
      Network.PALM_TESTNET,
      Network.POLYGON_MUMBAI,
      Network.POLKADOT_TESTNET,
      Network.RSK_TESTNET,
      Network.SOLANA_DEVNET,
      Network.STELLAR_TESTNET,
      Network.TEZOS_TESTNET,
      Network.TRON_SHASTA,
      Network.VECHAIN_TESTNET,
      Network.XDC_TESTNET,
      Network.XRP_TESTNET,
      Network.ZCASH_TESTNET,
      Network.ZILLIQA_TESTNET,
    ],
  },
}
