/**
 *
 * @export
 * @interface ScryptaUTXO
 */
export interface ScryptaUTXO {
    /**
     *
     * @type {number}
     * @memberof ScryptaUTXO
     */
    block: number;
    /**
     * Amount of UTXO in satoshis.
     * @type {number}
     * @memberof ScryptaUTXO
     */
    amount: number;
    /**
     * Data generated by a spender which is almost always used as variables to satisfy a pubkey script.
     * @type {string}
     * @memberof ScryptaUTXO
     */
    scriptPubKey: string;
    /**
     * Transaction hash.
     * @type {string}
     * @memberof ScryptaUTXO
     */
    txid: string;
    /**
     * Transaction index of the output.
     * @type {number}
     * @memberof ScryptaUTXO
     */
    vout: number;
    /**
     * Transaction reedemed flag.
     * @type {number}
     * @memberof ScryptaUTXO
     */
    redeemed: boolean;
}