name: Report a bug
description: Tell us about a bug or issue you may have identified in TatumSDK.
title: "Provide a general summary of the issue"
labels: [bug]
assignees: "-"
body:
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the issue
      description: Provide a summary of the issue and what you expected to happen, including specific steps to reproduce.
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: What operating system(s) are you seeing the problem on?
      multiple: true
      options:
        - Windows
        - macOS
        - Android
        - iOS
        - Linux
    validations:
      required: true
  - type: dropdown
    id: environment
    attributes:
      label: What environment do you see the problem on (Web/Node)?
      options:
        - Web
        - NodeJS
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: What version of tatum sdk are you using?
      placeholder: "e.g., v2.0.0"
    validations:
      required: true
