export enum AddressEventNotificationChain {
  ETH = 'ETH',
  SOL = 'SOL',
  XRP = 'XRP',
  MATIC = 'MATIC',
  CELO = 'CELO',
  KLAY = 'KLAY',
  BTC = 'BTC',
  LTC = 'LTC',
  BCH = 'BCH',
  DOGE = 'DOGE',
  TRON = 'TRON',
  BSC = 'BSC',
  TEZOS = 'TEZOS',
  EON = 'EON',
  CHZ = 'CHZ',
  FLR = 'FLR',
}
