import { Currency } from './Currency'

export enum AddressEventNotificationChain {
  ETH = Currency.ETH,
  SOL = Currency.SOL,
  XRP = Currency.XRP,
  MATIC = Currency.MATIC,
  CELO = Currency.CELO,
  KLAY = Currency.KLAY,
  BTC = Currency.BTC,
  LTC = Currency.LTC,
  BCH = Currency.BCH,
  DOGE = Currency.DOGE,
  TRON = Currency.TRON,
  BSC = Currency.BSC,
  TEZOS = Currency.TEZOS,
  EON = Currency.EON,
  CHZ = Currency.CHZ,
  FLR = Currency.FLR,
  CRO = Currency.CRO,
  BASE = Currency.ETH_BASE,
  AVAX = Currency.AVAX,
  FTM = Currency.FTM,
  OP = Currency.ETH_OP,
  ARB = Currency.ETH_ARB,
  BERA = Currency.BERA,
  MON = Currency.MON,
  UNI = Currency.ETH_UNI,
}
