export enum Currency {
  BTC = 'BTC',
  REVV = 'REVV',
  SAND = 'SAND',
  ADA = 'ADA',
  BCH = 'BCH',
  BNB = 'BNB',
  LTC = 'LTC',
  ONE = 'ONE',
  ETH = 'ETH',
  EGLD = 'EGLD',
  MATIC = 'MATIC',
  GAMEE = 'GAMEE',
  MATIC_ETH = 'MATIC_ETH',
  USDC_MATIC = 'USDC_MATIC',
  USDC_BSC = 'USDC_BSC',
  RMD = 'RMD',
  GMC = 'GMC',
  GMC_BSC = 'GMC_BSC',
  CELO = 'CELO',
  COIIN = 'COIIN',
  CUSD = 'CUSD',
  CEUR = 'CEUR',
  FLOW = 'FLOW',
  FUSD = 'FUSD',
  BSC = 'BSC',
  XDC = 'XDC',
  QTUM = 'QTUM',
  DOGE = 'DOGE',
  XRP = 'XRP',
  XLM = 'XLM',
  USDT = 'USDT',
  TRON = 'TRON',
  LEO = 'LEO',
  LINK = 'LINK',
  FREE = 'FREE',
  MKR = 'MKR',
  USDC = 'USDC',
  UNI = 'UNI',
  BAT = 'BAT',
  TUSD = 'TUSD',
  PAX = 'PAX',
  PLTC = 'PLTC',
  XCON = 'XCON',
  MMY = 'MMY',
  PAXG = 'PAXG',
  VET = 'VET',
  HAG = 'HAG',
  BETH = 'BETH',
  BUSD = 'BUSD',
  BBTC = 'BBTC',
  BADA = 'BADA',
  WBNB = 'WBNB',
  BDOT = 'BDOT',
  BXRP = 'BXRP',
  BLTC = 'BLTC',
  BBCH = 'BBCH',
  CAKE = 'CAKE',
  GLMR = 'GLMR',
  BUSD_BSC = 'BUSD_BSC',
  B2U_BSC = 'B2U_BSC',
  WBTC = 'WBTC',
  USDT_TRON = 'USDT_TRON',
  USDT_MATIC = 'USDT_MATIC',
  LATOKEN = 'LATOKEN',
  INRT_TRON = 'INRT_TRON',
  ALGO = 'ALGO',
  SOL = 'SOL',
  KCS = 'KCS',
  KLAY = 'KLAY',
  NEO = 'NEO',
}

export const ERC20_CURRENCIES = [
  Currency.USDT.toString(),
  Currency.LATOKEN.toString(),
  Currency.LEO.toString(),
  Currency.LINK.toString(),
  Currency.UNI.toString(),
  Currency.FREE.toString(),
  Currency.MKR.toString(),
  Currency.BUSD.toString(),
  Currency.USDC.toString(),
  Currency.MATIC_ETH.toString(),
  Currency.BAT.toString(),
  Currency.WBTC.toString(),
  Currency.TUSD.toString(),
  Currency.PAX.toString(),
  Currency.PAXG.toString(),
  Currency.PLTC.toString(),
  Currency.XCON.toString(),
  Currency.MMY.toString(),
  Currency.COIIN.toString(),
  Currency.REVV.toString(),
  Currency.SAND.toString(),
  Currency.GMC.toString(),
]

export const BEP20_CURRENCIES = [
  Currency.BETH.toString(),
  Currency.BBTC.toString(),
  Currency.RMD.toString(),
  Currency.USDC_BSC.toString(),
  Currency.B2U_BSC.toString(),
  Currency.BADA.toString(),
  Currency.WBNB.toString(),
  Currency.GMC_BSC.toString(),
  Currency.BDOT.toString(),
  Currency.BXRP.toString(),
  Currency.BLTC.toString(),
  Currency.BBCH.toString(),
  Currency.HAG.toString(),
  Currency.CAKE.toString(),
  Currency.BUSD_BSC.toString(),
]

export const MATIC20_CURRENCIES = [Currency.USDC_MATIC.toString(), Currency.GAMEE.toString(), Currency.USDT_MATIC.toString()]

export const ETH_BASED_CURRENCIES = [Currency.ETH.toString(), ...ERC20_CURRENCIES]

export const MATIC_BASED_CURRENCIES = [Currency.MATIC.toString(), ...MATIC20_CURRENCIES]

export const BSC_BASED_CURRENCIES = [Currency.BSC.toString(), ...BEP20_CURRENCIES]
