export enum OrderBookSort {
  PRICE_ASC = 'PRICE_ASC',
  PRICE_DESC = 'PRICE_DESC',
  CREATED_ASC = 'CREATED_ASC',
  CREATED_DESC = 'CREATED_DESC',
  AMOUNT_ASC = 'AMOUNT_ASC',
  AMOUNT_DESC = 'AMOUNT_DESC',
  FILL_ASC = 'FILL_ASC',
  FILL_DESC = 'FILL_DESC',
  FEE_ASC = 'FEE_ASC',
  FEE_DESC = 'FEE_DESC',
}
