/**
 *
 * @export
 * @interface ScryptaUTXO
 */
export interface ScryptaUTXO {
    /**
     * Version of the UTXO.
     * @type {number}
     * @memberof ScryptaUTXO
     */
    version: number;
    /**
     *
     * @type {number}
     * @memberof ScryptaUTXO
     */
    height: number;
    /**
     * Amount of UTXO in satoshis.
     * @type {number}
     * @memberof ScryptaUTXO
     */
    value: number;
    /**
     * Data generated by a spender which is almost always used as variables to satisfy a pubkey script.
     * @type {string}
     * @memberof ScryptaUTXO
     */
    script: string;
    /**
     * Address of the owner of the UTXO.
     * @type {string}
     * @memberof ScryptaUTXO
     */
    address: string;
    /**
     * Coinbase transaction - miner fee.
     * @type {boolean}
     * @memberof ScryptaUTXO
     */
    coinbase: boolean;
    /**
     * Transaction hash.
     * @type {string}
     * @memberof ScryptaUTXO
     */
    hash: string;
    /**
     * Transaction index of the output.
     * @type {number}
     * @memberof ScryptaUTXO
     */
    index: number;
}