import { Network } from '../dto'

export const TestConst = {
  EXISTING_SUBSCRIPTION_ETH_ADDRESS: '0xbaf6dc2e647aeb6f510f9e318856a1bcd66c5e19',
  INVALID_ETH_ADDRESS: 'TLduuX5NWFucPPafLbj9eab6Znwrdm72Qv',
}

export const AddressEventNetworks = [
  Network.BITCOIN,
  Network.BITCOIN_TESTNET,
  Network.BITCOIN_CASH,
  Network.BITCOIN_CASH_TESTNET,
  Network.LITECOIN,
  Network.LITECOIN_TESTNET,
  Network.DOGECOIN,
  Network.DOGECOIN_TESTNET,
  Network.ETHEREUM,
  Network.ETHEREUM_SEPOLIA,
  Network.ETHEREUM_HOLESKY,
  Network.POLYGON,
  Network.POLYGON_MUMBAI,
  Network.CELO,
  Network.CELO_ALFAJORES,
  Network.SOLANA,
  Network.SOLANA_DEVNET,
  Network.BINANCE_SMART_CHAIN,
  Network.BINANCE_SMART_CHAIN_TESTNET,
  Network.KLAYTN,
  Network.KLAYTN_BAOBAB,
  Network.TRON,
  Network.TRON_SHASTA,
  Network.XRP,
  Network.XRP_TESTNET,
  Network.TEZOS,
  Network.FLARE,
]

export const IncomingNativeTxNetworks = [
  Network.BITCOIN,
  Network.BITCOIN_TESTNET,
  Network.LITECOIN,
  Network.LITECOIN_TESTNET,
  Network.DOGECOIN,
  Network.DOGECOIN_TESTNET,
  Network.ETHEREUM,
  Network.ETHEREUM_SEPOLIA,
  Network.ETHEREUM_HOLESKY,
  Network.POLYGON,
  Network.POLYGON_MUMBAI,
  Network.CELO,
  Network.CELO_ALFAJORES,
  Network.BINANCE_SMART_CHAIN,
  Network.BINANCE_SMART_CHAIN_TESTNET,
  Network.XRP,
  Network.XRP_TESTNET,
  Network.KLAYTN,
  Network.KLAYTN_BAOBAB,
  Network.TRON,
  Network.TRON_SHASTA,
  Network.SOLANA,
  Network.SOLANA_DEVNET,
  Network.XRP,
  Network.XRP_TESTNET,
  Network.TEZOS,
]

export const OutgoingNativeTxNetworks = [
  Network.BITCOIN,
  Network.BITCOIN_TESTNET,
  Network.LITECOIN,
  Network.LITECOIN_TESTNET,
  Network.ETHEREUM,
  Network.ETHEREUM_SEPOLIA,
  Network.ETHEREUM_HOLESKY,
  Network.POLYGON,
  Network.POLYGON_MUMBAI,
  Network.CELO,
  Network.CELO_ALFAJORES,
  Network.BINANCE_SMART_CHAIN,
  Network.BINANCE_SMART_CHAIN_TESTNET,
  Network.XRP,
  Network.XRP_TESTNET,
  Network.KLAYTN,
  Network.KLAYTN_BAOBAB,
  Network.TRON,
  Network.TRON_SHASTA,
  Network.SOLANA,
  Network.SOLANA_DEVNET,
  Network.XRP,
  Network.XRP_TESTNET,
  Network.TEZOS,
]

export const OutgoingFailedNetworks = [
  Network.ETHEREUM,
  Network.ETHEREUM_SEPOLIA,
  Network.ETHEREUM_HOLESKY,
  Network.POLYGON,
  Network.POLYGON_MUMBAI,
  Network.CELO,
  Network.CELO_ALFAJORES,
  Network.BINANCE_SMART_CHAIN,
  Network.BINANCE_SMART_CHAIN_TESTNET,
  Network.KLAYTN,
  Network.KLAYTN_BAOBAB,
  Network.TEZOS,
]

export const PaidFeeNetworks = [
  Network.ETHEREUM,
  Network.ETHEREUM_SEPOLIA,
  Network.ETHEREUM_HOLESKY,
  Network.POLYGON,
  Network.POLYGON_MUMBAI,
  Network.CELO,
  Network.CELO_ALFAJORES,
  Network.BINANCE_SMART_CHAIN,
  Network.BINANCE_SMART_CHAIN_TESTNET,
  Network.KLAYTN,
  Network.KLAYTN_BAOBAB,
  Network.TRON,
  Network.TRON_SHASTA,
  Network.XRP,
  Network.XRP_TESTNET,
  Network.TEZOS,
]

export const FungibleTxNetworks = [
  Network.ETHEREUM,
  Network.ETHEREUM_SEPOLIA,
  Network.ETHEREUM_HOLESKY,
  Network.POLYGON,
  Network.POLYGON_MUMBAI,
  Network.CELO,
  Network.CELO_ALFAJORES,
  Network.BINANCE_SMART_CHAIN,
  Network.BINANCE_SMART_CHAIN_TESTNET,
  Network.KLAYTN,
  Network.KLAYTN_BAOBAB,
  Network.TRON,
  Network.TRON_SHASTA,
  Network.SOLANA,
  Network.SOLANA_DEVNET,
  Network.TEZOS,
]

export const NftNetworks = [
  Network.ETHEREUM,
  Network.ETHEREUM_SEPOLIA,
  Network.ETHEREUM_HOLESKY,
  Network.POLYGON,
  Network.POLYGON_MUMBAI,
  Network.CELO,
  Network.CELO_ALFAJORES,
  Network.BINANCE_SMART_CHAIN,
  Network.BINANCE_SMART_CHAIN_TESTNET,
  Network.KLAYTN,
  Network.KLAYTN_BAOBAB,
  Network.TRON,
  Network.TRON_SHASTA,
  Network.SOLANA,
  Network.SOLANA_DEVNET,
  Network.TEZOS,
]

export const MultitokenNetworks = [
  Network.ETHEREUM,
  Network.ETHEREUM_SEPOLIA,
  Network.ETHEREUM_HOLESKY,
  Network.POLYGON,
  Network.POLYGON_MUMBAI,
  Network.CELO,
  Network.CELO_ALFAJORES,
  Network.BINANCE_SMART_CHAIN,
  Network.BINANCE_SMART_CHAIN_TESTNET,
  Network.KLAYTN,
  Network.KLAYTN_BAOBAB,
]

export const FailedTxPerBlockNetworks = [
  Network.ETHEREUM,
  Network.ETHEREUM_SEPOLIA,
  Network.ETHEREUM_HOLESKY,
  Network.POLYGON,
  Network.POLYGON_MUMBAI,
  Network.CELO,
  Network.CELO_ALFAJORES,
  Network.BINANCE_SMART_CHAIN,
  Network.BINANCE_SMART_CHAIN_TESTNET,
  Network.KLAYTN,
  Network.KLAYTN_BAOBAB,
  Network.TRON,
  Network.TRON_SHASTA,
  Network.SOLANA,
  Network.SOLANA_DEVNET,
  Network.TEZOS,
]

export const ContractAddressLogEventNetworks = [
  Network.ETHEREUM,
  Network.ETHEREUM_SEPOLIA,
  Network.ETHEREUM_HOLESKY,
  Network.POLYGON,
  Network.POLYGON_MUMBAI,
  Network.CELO,
  Network.CELO_ALFAJORES,
  Network.BINANCE_SMART_CHAIN,
  Network.BINANCE_SMART_CHAIN_TESTNET,
  Network.KLAYTN,
  Network.KLAYTN_BAOBAB,
]

export const InternalTxNetworks = [
  Network.ETHEREUM,
  Network.ETHEREUM_SEPOLIA,
  Network.ETHEREUM_HOLESKY,
  Network.CELO,
  Network.CELO_ALFAJORES,
  Network.TEZOS,
]
