name: 'Publish packages - manual run for alpha'

on:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: build-16
          path: dist
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
          scope: '@tatumcom'
          always-auth: true
      - run: '[ ! -z "$NODE_AUTH_TOKEN" ] && echo "Not empty"  ;yarn publish --access public'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.TATUM_COM_NPM_TOKEN }}
