name: 'Publish packages - manual run for alpha'

on:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: build
          
      - name: Display structure of downloaded files
        run: ls -R
